version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install flake8
      - run:
          name: Run Flake8 Linting
          command: flake8 expense_pal.py --max-line-length=100 -- statistics

  expense-pal:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Expense Pal welcome note"
          command: echo "Welcome to the Expense Pal CI/CD pipeline!"
      - run:
          name: "Install Python, Pip, and Tkinter"
          command: | 
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip python3-tk
      - run:
          name: "Install dependencies"
          command: pip3 install -r requirements.txt
      - run:
          name: "Run unit tests"
          command: python3 -m unittest discover -s tests

# Orchestrate jobs using workflows
workflows:
  expense-pal-workflow: # This is the name of the workflow
    # Inside the workflow, define the jobs to run 
    jobs:
      - expense-pal:
          requires:
            - lint
