version: 2.1

jobs:
  expense-pal:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Expense Pal"
          command: echo "Welcome to the Expense Pal CI/CD pipeline!"
      - run:
          name: "Run unit tests"
          command: python -m unittest discover -s tests

# Orchestrate jobs using workflows
workflows:
  expense-pal-workflow: # This is the name of the workflow
    # Inside the workflow, define the jobs to run 
    jobs:
      - expense-pal
